on: push
name: Test and Verify
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        uses: cedrickring/golang-action/go1.14@1.5.2
        with:
          args: go test -race -coverprofile=coverage.txt -covermode=atomic
        env:
          GO111MODULE: "on"

      - name: Upload coverage
        uses: codecov/codecov-action@v1

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.26

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
